//
// L21S01 - Simple Database query
//

// Get and display numbers on all incidents
var incGr = new GlideRecord('incident');
incGr.query();

while (incGr.next()) {

  gs.info(incGr.getValue('number'));
}

// ACHTUNG incGr.getValue('number') == incGr.number not always!!
gs.info(typeof incGr.getValue('number')); // string
gs.info(typeof incGr.number); // object


// Rosa's code
var incGr = new GlideRecord('incident');

gs.info(Object.keys(incGr));  // sys_meta

gs.info(JSON.stringify(incGr, null, 2));
/*
*** Script: {
  "sys_meta": {
    "active": "1",
    "array": "0",
    "attributes": "all_tables.query_hints=true,email_client=true,hasWorkflow=true,live_feed=true,query_hints=true",
    "audit": "1",
    "calculation": "",
    "choice": "1",
    "choice_field": "",
    "choice_table": "",
    "create_roles": "",
    "default_value": "",
    "delete_roles": "itil_admin",
    "dependent": "",
    "dependent_on_field": "",
    "display": "number",
    "dynamic_creation": "0",
    "dynamic_creation_script": "",
    "dynamic_default_value": "",
    "dynamic_ref_qual": "",
    "element_reference": "0",
    "filterable": "1",
    "foreign_database": "",
    "function_definition": "",
    "function_field": "0",
    "groupable": "1",
    "help": "",
    "hint": "",
    "i18n_sortable": "1",
    "internal_type": "collection",
    "label": "Incident",
    "language": "en",
    "mandatory": "0",
    "matchable": "1",
    "max_length": "40",
    "multi_text": "0",
    "name": "incident",
    "plural": "Incidents",
    "primary": "0",
    "read_only": "0",
    "read_roles": "",
    "reference": "",
    "reference_cascade_rule": "",
    "reference_floats": "0",
    "reference_key": "",
    "reference_qual": "",
    "reference_qual_condition": "",
    "reference_type": "",
    "sizeclass": "116",
    "sortable": "1",
    "spell_check": "0",
    "staged": "0",
    "sys_package": "b90b461598f100107f2c2ed01a1f1664",
    "sys_scope": "global",
    "table_reference": "0",
    "text_index": "1",
    "type": "0",
    "type_description": "collection",
    "unique": "0",
    "url": "",
    "url_target": "",
    "use_dynamic_default": "0",
    "use_reference_qualifier": "simple",
    "virtual": "0",
    "widget": "",
    "write_roles": "",
    "xml_view": "0"
  }
}
*/

// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
var incGr = new GlideRecord('incident');
incGr.query();

gs.info(Object.keys(incGr));
/*
*** Script: sys_meta,parent,made_sla,caused_by,watch_list,upon_reject,sys_updated_on,child_incidents,hold_reason,approval_history,
skills,number,resolved_by,sys_updated_by,opened_by,user_input,sys_created_on,sys_domain,state,sys_created_by,knowledge,order,calendar_stc,
closed_at,cmdb_ci,delivery_plan,impact,contract,active,work_notes_list,business_service,priority,sys_domain_path,rfc,time_worked,
rejection_goto,expected_start,opened_at,business_duration,group_list,work_end,reopened_time,resolved_at,caller_id,approval_set,subcategory,
wf_activity,work_notes,short_description,close_code,correlation_display,delivery_task,work_start,assignment_group,business_stc,
additional_assignee_list,description,calendar_duration,notify,sys_class_name,service_offering,close_notes,closed_by,follow_up,
parent_incident,sys_id,contact_type,reopened_by,incident_state,urgency,u_cd_reference,problem_id,company,reassignment_count,
activity_due,assigned_to,u_test_rosa,severity,variables,variable_pool,hierarchical_variables,comments,sla_due,approval,
comments_and_work_notes,due_date,sys_mod_count,reopen_count,sys_tags,escalation,upon_approval,correlation_id,location,category
*/

gs.info(JSON.stringify(incGr, null, 2));
/*
*** Script: {
  "sys_meta": {
    "active": "1",
    "array": "0",
    "attributes": "all_tables.query_hints=true,email_client=true,hasWorkflow=true,live_feed=true,query_hints=true",
    "audit": "1",
    "calculation": "",
    "choice": "1",
    "choice_field": "",
    "choice_table": "",
    "create_roles": "",
    "default_value": "",
    "delete_roles": "itil_admin",
    "dependent": "",
    "dependent_on_field": "",
    "display": "number",
    "dynamic_creation": "0",
    "dynamic_creation_script": "",
    "dynamic_default_value": "",
    "dynamic_ref_qual": "",
    "element_reference": "0",
    "filterable": "1",
    "foreign_database": "",
    "function_definition": "",
    "function_field": "0",
    "groupable": "1",
    "help": "",
    "hint": "",
    "i18n_sortable": "1",
    "internal_type": "collection",
    "label": "Incident",
    "language": "en",
    "mandatory": "0",
    "matchable": "1",
    "max_length": "40",
    "multi_text": "0",
    "name": "incident",
    "plural": "Incidents",
    "primary": "0",
    "read_only": "0",
    "read_roles": "",
    "reference": "",
    "reference_cascade_rule": "",
    "reference_floats": "0",
    "reference_key": "",
    "reference_qual": "",
    "reference_qual_condition": "",
    "reference_type": "",
    "sizeclass": "116",
    "sortable": "1",
    "spell_check": "0",
    "staged": "0",
    "sys_package": "b90b461598f100107f2c2ed01a1f1664",
    "sys_scope": "global",
    "table_reference": "0",
    "text_index": "1",
    "type": "0",
    "type_description": "collection",
    "unique": "0",
    "url": "",
    "url_target": "",
    "use_dynamic_default": "0",
    "use_reference_qualifier": "simple",
    "virtual": "0",
    "widget": "",
    "write_roles": "",
    "xml_view": "0"
  },
  "parent": {},
  "made_sla": {},
  "caused_by": {},
  "watch_list": {},
  "upon_reject": {},
  "sys_updated_on": {},
  "child_incidents": {},
  "hold_reason": {},
  "approval_history": {},
  "skills": {},
  "number": {},
  "resolved_by": {},
  "sys_updated_by": {},
  "opened_by": {},
  "user_input": {},
  "sys_created_on": {},
  "sys_domain": {},
  "state": {},
  "sys_created_by": {},
  "knowledge": {},
  "order": {},
  "calendar_stc": {},
  "closed_at": {},
  "cmdb_ci": {},
  "delivery_plan": {},
  "impact": {},
  "contract": {},
  "active": {},
  "work_notes_list": {},
  "business_service": {},
  "priority": {},
  "sys_domain_path": {},
  "rfc": {},
  "time_worked": {},
  "rejection_goto": {},
  "expected_start": {},
  "opened_at": {},
  "business_duration": {},
  "group_list": {},
  "work_end": {},
  "reopened_time": {},
  "resolved_at": {},
  "caller_id": {},
  "approval_set": {},
  "subcategory": {},
  "wf_activity": {},
  "work_notes": {},
  "short_description": {},
  "close_code": {},
  "correlation_display": {},
  "delivery_task": {},
  "work_start": {},
  "assignment_group": {},
  "business_stc": {},
  "additional_assignee_list": {},
  "description": {},
  "calendar_duration": {},
  "notify": {},
  "sys_class_name": {},
  "service_offering": {},
  "close_notes": {},
  "closed_by": {},
  "follow_up": {},
  "parent_incident": {},
  "sys_id": {},
  "contact_type": {},
  "reopened_by": {},
  "incident_state": {},
  "urgency": {},
  "u_cd_reference": {},
  "problem_id": {},
  "company": {},
  "reassignment_count": {},
  "activity_due": {},
  "assigned_to": {},
  "u_test_rosa": {},
  "severity": {},
  "variables": {},
  "variable_pool": {},
  "hierarchical_variables": {},
  "comments": {},
  "sla_due": {},
  "approval": {},
  "comments_and_work_notes": {},
  "due_date": {},
  "sys_mod_count": {},
  "reopen_count": {},
  "sys_tags": {},
  "escalation": {},
  "upon_approval": {},
  "correlation_id": {},
  "location": {},
  "category": {}
}
*/